.gitignore, .pep8, .pylintrc, .travis.yml, AUTHORS, LICENSE, edxsearch/__init__.py, edxsearch/settings.py, edxsearch/urls.py, edxsearch/wsgi.py, manage.py, requirements.txt, search/__init__.py, search/api.py, search/elastic.py, search/filter_generator.py, search/result_processor.py, search/search_engine_base.py, search/tests/__init__.py, search/tests/mock_search_engine.py, search/tests/tests.py, search/urls.py, search/utils.py, search/views.py, settings.py, setup.py
@chrisndodge, @ormsbee Moved this work into edx repo. Please continue comments in here.
@dsego , @dino-cikatic , @marjev - FYI
=> First pass for review

search/elastic.py, search/search_engine_base.py, search/tests/mock_search_engine.py, search/tests/test_mock_search_engine.py, search/tests/test_views.py, search/tests/tests.py, search/tests/utils.py
=> Supports SOL-180. Allows for ids to be excluded from a search.

search/result_processor.py, search/tests/test_search_result_processor.py
@martynjames I've opened a PR that contains removal of the ellipsis from the search results here.
I will have a 2nd PR for this ticket on the edx-platform repo, which will contain css style.
=> (SOL-294) Remove Ellipsis from Search app

search/elastic.py, search/tests/mock_search_engine.py, search/tests/tests.py, search/utils.py
@martynjames 
Not sure if this is the right way to do it, but it fixes the bokchoy tests for dashboard search. I did not write a unit test for this change yet.
=> support lists in field_value

search/api.py, search/tests/mock_search_engine.py, search/tests/test_course_discovery.py, search/tests/test_course_discovery_views.py, search/tests/test_views.py, search/tests/tests.py, search/tests/utils.py, search/urls.py, search/views.py
For first review (@mattdrayer) This is the search-side changes to enable course discovery
=> First pass at course discovery search - SOL-280

search/api.py, search/tests/test_course_discovery.py, search/tests/test_course_discovery_views.py, search/views.py
@dino-cikatic - Filtering addition to course discovery code...
=> Add filtering

search/api.py, search/initializer.py, search/tests/test_course_discovery.py, search/tests/test_course_discovery_views.py, search/tests/tests.py, search/views.py
@martynjames this is a base class to support SOL-487 on edx-platform.
=> SOL-487 Add SearchInitializer

search/api.py, search/elastic.py, search/search_engine_base.py, search/tests/mock_search_engine.py, search/tests/test_course_discovery.py, search/tests/test_engines.py, search/tests/tests.py, search/views.py
@dino-cikatic - Branch for facet results.
=> Add faceting results to course discovery

search/tests/mock_search_engine.py
@marjev @vkaracic  
This should sort out the problems with some tests failing in the edx-platform.
=> unicodefiy SOL-1069

search/elastic.py, search/tests/test_engines.py
=> Allow elasticsearch to be configurable

search/tests/mock_search_engine.py
We discovered that the MockSearchEngine was not escaping queries in the same way as the regular one. The symptom was that code could pass tests even if it was invoking the search engine with incorrectly escaped strings. I've changed the mock engine to use the same escaping logic as the main engine so that we can catch these bugs earlier.
=> Make MockSearchEngine escape queries correctly

requirements.txt, setup.py, test_requirements.txt
=> upgrade to django 1.8

requirements.txt, setup.py, test_requirements.txt
=> Revert "upgrade to django 1.8"

requirements.txt
TNL-3820
@symbolist @macdiesel @doctoryes @nedbat PTAL. Thanks!
=> update event-tracking version

setup.py
This was originally done in this commit: https://github.com/edx/edx-search/commit/3e633b71692068166f0c3ba19b563e2635ec1535
=> Update version and use search test packages.

.travis.yml, Makefile, edxsearch/urls.py, search/tests/test_search_result_processor.py, search/urls.py, setup.py, test_requirements.txt, tox.ini
=> Upgrade to django 1.11 and implemented tox

edxsearch/settings.py, edxsearch/urls.py, edxsearch/wsgi.py, manage.py, search/api.py, search/elastic.py, search/filter_generator.py, search/initializer.py, search/result_processor.py, search/search_engine_base.py, search/tests/mock_search_engine.py, search/tests/test_course_discovery.py, search/tests/test_course_discovery_views.py, search/tests/test_engines.py, search/tests/test_mock_search_engine.py, search/tests/test_search_result_processor.py, search/tests/test_views.py, search/tests/tests.py, search/tests/utils.py, search/urls.py, search/utils.py, search/views.py, settings.py, setup.py
Fixes https://openedx.atlassian.net/browse/INCR-96
$ __python-modernize -w .__
=> [INCR-96] Run python-modernize on edx-search

test_requirements.txt
Fixes: https://openedx.atlassian.net/browse/INCR-100
=> [INCR-100] Upgrade event tracking in edx-search

.travis.yml, search/elastic.py, search/result_processor.py, search/tests/mock_search_engine.py, test_requirements.txt, tox.ini
Fixes: https://openedx.atlassian.net/browse/INCR-102
=> [INCR-102] fix python-3.6 compatibility

setup.py
Fixes: https://openedx.atlassian.net/browse/INCR-106
=> [INCR-106] update trove classifiers with python 3.6 & django 2.[01] support

.travis.yml, requirements/base.txt, requirements/dev.txt, requirements/quality.in, requirements/quality.txt, requirements/testing.in, requirements/testing.txt, requirements/travis.txt, setup.py
Updating version number to get repo ready for another release.
=> PROD-384: Updated version number to 1.2.3

openedx.yaml, settings.py
Update owner to the technical lead
=> Change owner to azarembok

search/api.py, setup.py
https://openedx.atlassian.net/browse/BOM-1036
=> Revert out sorting changes that cause edx-platform tests to fail.

Makefile, edxsearch/settings.py, edxsearch/urls.py, edxsearch/wsgi.py, manage.py, search/api.py, search/elastic.py, search/filter_generator.py, search/initializer.py, search/result_processor.py, search/search_engine_base.py, search/tests/mock_search_engine.py, search/tests/test_course_discovery.py, search/tests/test_course_discovery_views.py, search/tests/test_engines.py, search/tests/test_mock_search_engine.py, search/tests/test_search_result_processor.py, search/tests/test_views.py, search/tests/tests.py, search/tests/utils.py, search/urls.py, search/utils.py, search/views.py, settings.py, setup.py
Relevant JIRA issue [here](https://openedx.atlassian.net/browse/BOM-1766).
=> Removed deprecated future imports

requirements/base.in, requirements/base.txt, requirements/dev.txt, requirements/travis.txt, search/elastic.py, search/result_processor.py, search/tests/mock_search_engine.py, search/tests/test_views.py, search/utils.py, search/views.py
**Issue:** [BOM-1816](https://openedx.atlassian.net/browse/BOM-1816)
- Remove usage of package `six`.
=> Remove usage of package six

Makefile, requirements/base.txt, requirements/dev.txt, requirements/quality.txt, requirements/testing.in, requirements/testing.txt, requirements/travis.txt
Added target for test & clean
**Packages added**
- pytest-cov
=> [BD-18] Standardize the make test targets

search/tests/mock_search_engine.py, setup.py
Add the ability for the MockSearchEngine to accept kwargs for indexing.
=> Allow kwargs for the mock search engine indexing.

.travis.yml, setup.py, tox.ini
JIRA: https://openedx.atlassian.net/browse/BOM-2694
=> feat: Added support for django3.2

.github/workflows/ci.yml, Makefile, edxsearch/__init__.py, requirements/base.txt, requirements/ci.txt, requirements/constraints.txt, requirements/dev.txt, requirements/pip-tools.txt, requirements/pip.txt, requirements/quality.txt, requirements/testing.txt, tox.ini
feat!: Dropped django22 support.
upgrade packages.
=> feat!: Dropped django22 support.

.github/workflows/upgrade-python-requirements.yml, catalog-info.yaml
- Add catalog-info.yaml
- Add python upgrade file
=> chore: add catalog info and python upgrade file

edxsearch/__init__.py
Bump version from 4.1.1 to 4.1.2.
=> fix: bump version to 4.1.2
