openedx/edx-search

- search/elastic.py
- search/tests/mock_search_engine.py
- search/tests/tests.py
- search/views.py
@mattdrayer - any chance you could look at this.
We were having a failure in the call to elasticsearch if the search included characters that are in the "reserved" characters for elasticsearch.
Since analyzing removes these characters anyway, we simply strip them out of our search term - the alternative is to escape them if we need to match, but that does not appear to be working in the elasticsearch version that we are currently using.
> Addresses search exception when including reserved characters in search

- search/elastic.py
- search/tests/tests.py
so that explicit calls for when no value is specified are honoured.
@dino-cikatic - Please review this change, I think we'll want it to support SOL-495 correctly.
@dsego, @mattdrayer  - Seems like a small bug fix, so can either (or both) of you be the second reviewer(s)?
> Support `None` value for filter_dictionary attribute

- search/tests/mock_search_engine.py
@marjev, @dino-cikatic, @dsego  - easy fix to mock search engine to support where filtering upon `None` value. Any 2 thumbs will do!
> Support None values in filter specification

- search/api.py
- search/elastic.py
- search/filter_generator.py
- search/search_engine_base.py
- search/tests/mock_search_engine.py
- search/tests/tests.py
Addresses SOL-825 & SOL-826 (along with changes to platform - https://github.com/edx/edx-platform/pull/7914)
This change adds the ability for search clients to specify certain field/value pairs to exclude from results, which supports filtering-out of certain documents
> Add exclude filtering to allow for microsites

- test_requirements.txt
Preparation for the [Django 1.8 upgrade](https://openedx.atlassian.net/wiki/display/TNL/Library+updates+needed+for+Django+upgrade+to+1.8)
> Upgrade mock-django to 0.6.9

- .travis.yml
- search/elastic.py
- search/tests/test_engines.py
- search/tests/tests.py
- setup.py
Elasticsearch 0.90.x is quite out-of-date, and this requirement is preventing us from sharing an ES cluster with newer IDAs.
Also includes code/requirements cleanup.
ECOM-3261 and SOL-295
Merge #38 first.
Please review: @muhammad-ammar @macdiesel @andy-armstrong @bderusha 
FYI @cpennington @e0d @feanil
> Elasticsearch Update

- setup.py
This is required for tests in the edx-platform repo to run,
as they reference tests.mock_search_engine.
@clintonb
> Install the tests subpackage as part of this package

- .coveragerc
- .travis.yml
- codecov.yml
- test_requirements.txt
Removes Coveralls from our Travis builds and introduces CodeCov in its place.
@bjacobel could you confirm that this CodeCov report looks the way we expect it to?
@robrap for a second review.
> Switch to using CodeCov for coverage checking.

- .gitignore
- search/api.py
- search/elastic.py
- search/tests/mock_search_engine.py
- search/tests/test_course_discovery.py
- search/tests/test_course_discovery_views.py
- search/tests/test_views.py
- search/tests/utils.py
- search/views.py
- setup.py
- test_requirements.txt
Remove the hyphen and double quote from the list of reserved characters in Elastic searches, allowing more effective searches for hyphenated terms and quoted phrases.
This introduces the possibility of Elastic rejecting malformed quoted queries, so additional exception handling is provided for that case. Actually presenting the more specific errors to users requires changes in edx-platform; installing this revision of edx-search without those changes will result in malformed queries producing the same "There was an error, try searching again." message any search error returns.
**Testing instructions**:
To test manually:
1. Enable search in your devstack by setting the following settings to True in cms/envs/devstack_docker.py and lms/envs/devstack_docker.py:
* ENABLE_COURSEWARE_SEARCH
* …
> Reduce set of reserved characters in Elastic searches

- .travis.yml
- pycodestyle
- search/tests/test_search_result_processor.py
- search/views.py
- test_requirements.txt
- tox.ini
https://openedx.atlassian.net/browse/INCR-85
Opened #64
> [INCR-85] Support testing Python 3 in edx-search

- search/api.py
Course discovery was unable to use SearchFilterGenerator for custom field filters because it only recognized `org`. In our case for example, we needed to autofilter with a select group of course ids.
This change is backwards compatible.
@nedbat
> Remove hardcoded field filter to allow custom discovery search fields

- openedx.yaml
edx-search already complied with OEP-7 due to this [PR](https://github.com/edx/edx-search/pull/65). Here I just update the openedx.yaml to reflect true state of repository.
> Updating openedx.yaml to confirm OEP-7 compliance

- search/api.py
- setup.py
Our instance needs this for the empty query to return the courses sorted by their start date.
> Allow discovery search results to be sorted

- search/api.py
- setup.py
This reverts commit a202ec5b635061bb0ecbe67e645aa773d692cea7.
Also bump version number up.
This commit caused tests to fail on edx-platform. This revert should allow us to use the latest version of edx-search on edx-platform again.
https://openedx.atlassian.net/browse/BOM-1036
> Revert "Allow discovery search results to be sorted"

- .travis.yml
- edxsearch/settings.py
- requirements/base.in
- requirements/base.txt
- requirements/dev.txt
- requirements/pip-tools.txt
- requirements/quality.txt
- requirements/testing.txt
- requirements/travis.txt
- settings.py
- setup.py
- tox.ini
- Unconstrain Django for 2.2 upgrade
- Remove `TEMPLATE_DEBUG` setting, which is deprecated
- Add templates definition -- required for admin app in Django 2.2
- Include py35-django22 testing
- Drop testing on Python > 3.5 except for most recent Django (quality check fails for these due to dependency conflict; probably will not be a problem when 2.7 is dropped)
> Relax Django constraint for upgrade to 2.2

- .travis.yml
- Makefile
- README.md
- docker-compose.yml
- requirements/base.in
- requirements/base.txt
- requirements/constraints.txt
- requirements/dev.txt
- requirements/pip-tools.txt
- requirements/quality.txt
- requirements/testing.txt
- requirements/travis.txt
- search/api.py
- search/elastic.py
- search/search_engine_base.py
- search/tests/mock_search_engine.py
- search/tests/test_course_discovery.py
- search/tests/test_course_discovery_views.py
- search/tests/test_engines.py
- search/tests/test_mock_search_engine.py
- search/tests/test_views.py
- search/tests/tests.py
- search/tests/utils.py
- search/views.py
- setup.py
**Description:** transition from es1.5 to es7. Replaces index `courseware_index` with doc_types `courseware_content` and `course_info` to indexes `courseware_content` and `course_info`
**Was done:**
**Code coverage:** 99%
**Notes:** 
* Changes to the edx-platform which apply edx-search updates
> [BD-19] Transition to the Elasticsearch 7.8.0 version

- edxsearch/__init__.py
- requirements/ci.txt
- requirements/dev.txt
- requirements/pip.in
- requirements/pip.txt
- requirements/quality.txt
Major version was bumped in this [PR](https://github.com/openedx/edx-search/pull/120) which was a mistake. This PR fixes that mistake. Also `setuptools` constraint was not advertised in the `pip.in` requirements file which is also fixed in this PR.
> Fix issues with setuptools pin

- edxsearch/__init__.py
- search/result_processor.py
- search/tests/test_search_result_processor.py
- search/utils.py
Multiple matches are merged with `ELLIPSIS` as a separator.
This reverses the order of operations so that the matches are decorated before they are merged. This way, the content of `ELLIPSIS` is not decorated with HTML `<b>` tags.
Jira ticket (nonpublic): [BB-5589](https://tasks.opencraft.com/browse/BB-5589)
1. Add the following to `{lms,cms}/envs/private.py`:
```python
from .common import FEATURES
FEATURES['ENABLE_COURSEWARE_SEARCH'] = True
FEATURES['ENABLE_COURSEWARE_SEARCH_FOR_COURSE_STAFF'] = True
FEATURES['ENABLE_DASHBOARD_SEARCH'] = True
FEATURES['ENABLE_COURSE_DISCOVERY'] = True
FEATURES['ENABLE_COURSEWARE_INDEX'] = True
FEATURES['ENABLE_LIBRARY_INDEX'] = True
ELASTIC_SEARCH_CONFIG = [
{
'use_ssl': False,
'host': 'edx.devstack.elasticsearch710',
'port': 9200
}
]
```
2. Go to the …
> fix: do not decorate `ELLIPSIS` with `<b>` tags

- edxsearch/__init__.py
- search/result_processor.py
- search/tests/test_search_result_processor.py
We're using [shlex](https://docs.python.org/3.8/library/shlex.html) to split phrases. It uses the POSIX mode by default, which is throwing an exception when there are unclosed quotes in phrases. This escapes such quotes, so the phrases with apostrophes can be split correctly.
OSPR ticket: [OSPR-6172](https://openedx.atlassian.net/browse/OSPR-6172)
OpenCraft Jira ticket: [BB-4994](https://tasks.opencraft.com/browse/BB-4994)
The ElasticSearch connection was not working for me with the most recent devstack version. I had to add this to `lms/envs/private.py` and `cms/envs/private.py`:
```python
ELASTIC_SEARCH_CONFIG = [
{
'use_ssl': False,
'host': 'edx.devstack.elasticsearch710',
'port': 9200
}
]
```
1. Enable `FEATURES['ENABLE_COURSEWARE_SEARCH']` in LMS.
1. Enable …
> fix: handle phrases with apostrophes

- requirements/base.txt
- requirements/dev.txt
- requirements/quality.txt
Updates `django` from `3.2.14` to `3.2.17`
> chore: Updating Python Requirements

- README.md
- edxsearch/__init__.py
- search/elastic.py
- search/tests/test_engines.py
- search/tests/tests.py
**This PR is a redo of https://github.com/openedx/edx-search/pull/128, because there was an issue with the tests running**
Add a new setting `ELASTIC_SEARCH_INDEX_PREFIX` that will be prepended to all ElasticSearch indexes. This helps with multitenancy so that indexes can be split per "tenant"
- Proofread the code
- It should be enough to run the tests here as they are fairly extensive with `make test_with_es`
- [Related Grove PR](https://gitlab.com/opencraft/dev/grove/-/merge_requests/131) that will utilize this feature.
> chore: add ELASTIC_SEARCH_INDEX_PREFIX setting to prefix indices

- Makefile
- edxsearch/__init__.py
- search/api.py
- search/elastic.py
- search/search_engine_base.py
- search/tests/mock_search_engine.py
- search/tests/test_engines.py
- search/tests/tests.py
- search/views.py
We need to know exactly what we are asking elasticsearch sometimes to debug problems. But we would prefer not to log it for all uses or force logging on openedx in general.
After a bunch of cleanup to make working in here a little easier and a new make target for local installation, I added a new log parameter to the general search arg and activates it for elasticsearch. Then I added a setting to turn this flag on for courseware search which is the place we currently need it, other settings can come later if desired.
After this is ready I'll add a default setting of False in platform lms and a devstack setting of True, and then some settings for edX proper in the internal settings repo to turn it on.
Sample local log
> 2023-11-15 21:24:56,566 INFO 107 [search.elastic] [user None] [ip …
> Log detailed elasticsearch params

- edxsearch/__init__.py
- search/api.py
- search/tests/test_engines.py
- search/views.py
platform does not use this, but platform tests do, so the clarity is not worth the trouble and upgrade risk
> fix: cannot rename perform-search to clearer name, breaks tests

- search/api.py
- search/tests/test_api_timing_events.py
- search/utils.py
- search/views.py
For KBK-57
Adds a `edx.course.search.executed` event with timings for
- Filter generation
- Total search time
- Post-processing results
> feat: add timing for results filtering

- edxsearch/__init__.py
- setup.py
The default empty long_description is failing so make the README the long_description.  Without this change new deploys to PyPI will fail.
> docs: Add a long_description.

- edxsearch/__init__.py
- search/meilisearch.py
- search/tests/test_meilisearch.py
In `search.meilisearch.create_indexes`, we were not waiting for the index creation tasks to complete. This was causing a potential race condition, where the `create_indexes` function would fail because it took a few seconds for the index creation to succeed.
See the relevant conversation here:
https://github.com/openedx/edx-platform/pull/35743#issuecomment-2450115310
> feat: wait for meilisearch index creation to succeed

- search/meilisearch.py
The catalog_visibility filter is passed to the `courseware_content` index when performing a search using the legacy student dashboard view. If not included an error like follows is raised:
MeilisearchApiError. Error code: invalid_search_filter. Error message:
Attribute `catalog_visibility` is not filterable
I didn't dive to deep on this, but seems like the filter is added by the [`LmsSearchFilterGenerator`](https://github.com/openedx/edx-platform/blob/master/lms/lib/courseware_search/lms_filter_generator.py#L63-L66).
The normal course search in the Learning MFE doesn't throw any errors because the additional filters are not added when the search is [narrowed to a single course](https://github.com/openedx/edx-platform/blob/9cade7a3488eee24109311cb145747a01348df14/lms/lib/courseware_search/l …
> fix: include catalog_visibility filter in courseware_content

- .github/workflows/ci.yml
- edxsearch/__init__.py
- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- requirements/quality.txt
- requirements/testing.txt
- setup.py
- tox.ini
Closes:  #193 
Adds tox and CI testing support for Django 5.2. Also, ran upgrade for updating existing dependencies.
> chore: Add support for Django 5.2
